# Generated by Django 2.0.7 on 2018-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_product', models.ImageField(help_text='302x200px', upload_to='images/', verbose_name='загрузка фото')),
                ('title_name', models.CharField(max_length=100, verbose_name='Название')),
                ('description_product', models.TextField(verbose_name='Описание товара')),
                ('cloth_characteristic', models.TextField(verbose_name='ткань')),
                ('color_characteristic', models.TextField(verbose_name='цвета')),
                ('size_characteristic', models.TextField(verbose_name='размеры')),
                ('Price_product', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Значение должно быть 'slides1'", max_length=7, verbose_name='Для разработчиков(не трогать)')),
                ('slide_1', models.ImageField(help_text='920x230px', upload_to='slides/', verbose_name='Слайд 1')),
                ('slide_2', models.ImageField(help_text='920x230px', upload_to='slides/', verbose_name='Слайд 2')),
                ('slide_3', models.ImageField(help_text='920x230px', upload_to='slides/', verbose_name='Слайд 3')),
            ],
        ),
    ]
