# Generated by Django 2.0.7 on 2018-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_slides_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_product_slide_1',
            field=models.ImageField(default=0, help_text='604x400px', upload_to='images/', verbose_name='загрузка фото слайда 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo_product_slide_2',
            field=models.ImageField(blank=True, help_text='604x400px', upload_to='images/', verbose_name='загрузка фото слайда 2'),
        ),
    ]
