# Generated by Django 2.0.7 on 2018-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180728_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slides',
            name='name',
        ),
    ]
